//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Persistency
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBDataIdentifier
    {
        public DBDataIdentifier()
        {
            this.DataItems = new HashSet<DBDataItem>();
        }
    
        public string DataUniqueID { get; set; }
        public Nullable<DBDataType> DataType { get; set; }
        public byte[] RawData { get; set; }
    
        public virtual ICollection<DBDataItem> DataItems { get; set; }
    }
}
