//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Persistency
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBDataParameter
    {
        public string DataItemID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string ID { get; set; }
        public string DataItemDataItemID { get; set; }
    
        public virtual DBDataItem DataItem { get; set; }
    }
}
