//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Persistency
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBDataItem
    {
        public DBDataItem()
        {
            this.DataParameters = new HashSet<DBDataParameter>();
        }
    
        public string DataItemID { get; set; }
        public string DataUniqueID { get; set; }
        public byte[] DataBytes { get; set; }
        public string Description { get; set; }
        public Nullable<long> Size { get; set; }
        public string DeviceID { get; set; }
        public string LocationID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string DataIdentifierDataUniqueID { get; set; }
    
        public virtual DBDataIdentifier DataIdentifier { get; set; }
        public virtual ICollection<DBDataParameter> DataParameters { get; set; }
    }
}
