//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Persistency
{
    using System;
    
    public enum DBDataType : int
    {
        Default = 0,
        AcquisitionResult = 1,
        TestResult = 2,
        TransactionStream = 3,
        PrintingRecord = 4,
        Other = 5
    }
}
