//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ResourceIntegrator
{

    public interface IResourceRouter
    {
        object Post(string uri, string data, Authentication authentication, Dictionary<string, string> headers);

        object Get(string uri, Authentication authentication, Dictionary<string, string> headers);

        void PostAsync(string uri, byte[] data, Authentication authentication, Dictionary<string, string> headers);

        void GetAsync(string uri, Authentication authentication, Dictionary<string, string> headers);

    }

}