//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace MES.Core
{
    [DataContract, Serializable]
    public class DataIdentifier
    {
        /// <summary>
        /// A value that globally and uniquely identifies and distinguishes the object the acquisition data represents
        /// </summary>
        [DataMember]
        public string DataUniqueID { get; set; }

        /// <summary>
        /// Original form of data that recoganizes each acquisition
        /// </summary>
        [DataMember, System.Xml.Serialization.XmlIgnore]
        public object RawData { get; set; }
    }
}