//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MES.Core
{
    public class DataPair
    {
        /// <summary>
        /// The globally unique identifier that correlates and groups all of the data items belonging to this data pair   
        /// </summary>
        public virtual DataIdentifier Identifier
        {
            get;
            set;
        }

        /// <summary>
        /// All of the data items belonging to this data pair
        /// </summary>
        public virtual List<DataItem> Items
        {
            get;
            set;
        }

    }
}