//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MES.Core
{
    /// <summary>
    /// An interface responsible for correlating the acquired data and the identifier that indicates 
    /// what the data represents and which it belongs to
    /// </summary>
    public interface ICorrelator
    {
        /// <summary>
        /// Correlates the acquired data as well as the identifier 
        /// that describes the entity that the data represents, 
        /// and outputs the data pair as the correlation result
        /// </summary>
        /// <param name="Identifier">The identifier that describes the entity that the data represents</param>
        /// <param name="Item">The data item containing the acquired data </param>
        /// <returns>Data pair as the correlation result</returns>
        DataPair Correlate(DataIdentifier Identifier, DataItem Item);
    }
}