//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MES.Core
{
    /// <summary>
    /// An interface responsible for computing/persisting the acquired data
    /// </summary>
    public interface IProcessor
    {
        /// <summary>
        /// Processes the acquired data
        /// </summary>
        /// <param name="Pair">The data pair containing the data to be processed</param>
        /// <returns>Processing result</returns>
        Result Process(DataPair Pair);

        DataPair Compute(DataPair Pair);

        DataPair Print(DataPair Pair, string DocumentName, string DataKeyName);
    }
}
