//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BarCodeDetector : IDetector
{
	public virtual void Notify(DataIdentifier Identifier)
	{
		throw new System.NotImplementedException();
	}

}

